POST http://localhost:5000/api/auth/login
content-type: application/json

{
    "email": "sample@sample.com453",
    "password": "samplepw44"
}

###

GET http://localhost:5000/api/webhooks

###
POST http://localhost:5000/api/webhooks/delete
Content-Type: application/json

{
    "ids": ["3453454wtrsfgd345", "djhkfg834973495t"]
}

###
POST http://localhost:5000/api/auth/tokens
Content-Type: application/json

{
    "email": "sample2@sample.com"
}

###
POST http://localhost:5000/api/auth/tokens/trello
Content-Type: application/json

{
    "email": "sample2@sample.com",
    "token": "3875673985hfgdkjfgjhk"
}

###
DELETE http://localhost:5000/api/webhooks?id=dfjkhgdjfg
Content-Type: application/json

{
    "email": "sample@smaple.com"
}

###
POST http://localhost:5000/api/receiver?listID=sample

###
HEAD http://49591fa11e40.ngrok.io/api/receiver?listID=5d597ff5bdea837eb5b639a5